### PR TITLE
[MRRESOURCES-122] Java 8 as minimum

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Review by michael-o — APPROVED** [review]
LGTM visually

**Comment by olamy** [comment]
build looks good. 
gha takes too long...

**Comment by slawekjaranowski** [comment]
> build looks good. gha takes too long...

Looks like GHA workers are too busy ... 
the most of time taks spent on waiting for free worker ...

😠

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #225

**Pull request merged**
